use ratatui::style::Color;
use ratatui::widgets::BorderType;

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum TreemapMode {
    HalfBlock,
    BlockChar(char),
}

pub struct UiStyle {
    pub name: &'static str,
    // Borders
    pub border_type: BorderType,
    pub border_color: Color,
    // Tree connectors
    pub tree_vertical: &'static str,
    pub tree_branch: &'static str,
    pub tree_last_child: &'static str,
    pub tree_expanded: &'static str,
    pub tree_collapsed: &'static str,
    // Progress bars
    pub bar_filled: &'static str,
    pub bar_empty: &'static str,
    pub ext_pastille: &'static str,
    // Treemap
    pub treemap_mode: TreemapMode,
    pub treemap_dir_bg: Color,
    pub treemap_empty_bg: Color,
    // Selection border chars
    pub sel_h: char,
    pub sel_v: char,
    pub sel_tl: char,
    pub sel_tr: char,
    pub sel_bl: char,
    pub sel_br: char,
    // Colors
    pub fg_directory: Color,
    pub fg_file: Color,
    pub fg_accent: Color,
    pub selected_bg: Color,
    pub selected_fg: Color,
    pub statusbar_bg: Color,
    pub pct_high: Color,
    pub pct_mid: Color,
    pub pct_low: Color,
    // Menu
    pub menu_bg: Color,
    pub menu_fg: Color,
    pub menu_active_bg: Color,
    pub menu_active_fg: Color,
    pub menu_drop_bg: Color,
    pub menu_drop_fg: Color,
    pub menu_drop_sel_bg: Color,
    pub menu_drop_sel_fg: Color,
    pub menu_shortcut_fg: Color,
}

pub const STYLE_COUNT: usize = 4;

pub fn all_styles() -> [&'static str; STYLE_COUNT] {
    ["Modern", "Classic DOS", "Retro CGA", "Minimal"]
}

pub fn style_by_index(index: usize) -> UiStyle {
    match index {
        0 => modern(),
        1 => classic_dos(),
        2 => retro_cga(),
        3 => minimal(),
        _ => modern(),
    }
}

pub fn modern() -> UiStyle {
    UiStyle {
        name: "Modern",
        border_type: BorderType::Rounded,
        border_color: Color::Rgb(60, 60, 70),
        tree_vertical: "│   ",
        tree_branch: "├── ",
        tree_last_child: "└── ",
        tree_expanded: "▼ ",
        tree_collapsed: "▶ ",
        bar_filled: "━",
        bar_empty: "░",
        ext_pastille: " ██ ",
        treemap_mode: TreemapMode::HalfBlock,
        treemap_dir_bg: Color::Rgb(40, 40, 40),
        treemap_empty_bg: Color::Rgb(20, 20, 25),
        sel_h: '━',
        sel_v: '┃',
        sel_tl: '┏',
        sel_tr: '┓',
        sel_bl: '┗',
        sel_br: '┛',
        fg_directory: Color::White,
        fg_file: Color::White,
        fg_accent: Color::Cyan,
        selected_bg: Color::DarkGray,
        selected_fg: Color::White,
        statusbar_bg: Color::Rgb(30, 30, 30),
        pct_high: Color::Red,
        pct_mid: Color::Yellow,
        pct_low: Color::Green,
        menu_bg: Color::Rgb(30, 30, 35),
        menu_fg: Color::White,
        menu_active_bg: Color::Cyan,
        menu_active_fg: Color::Black,
        menu_drop_bg: Color::Rgb(40, 40, 50),
        menu_drop_fg: Color::White,
        menu_drop_sel_bg: Color::Cyan,
        menu_drop_sel_fg: Color::Black,
        menu_shortcut_fg: Color::DarkGray,
    }
}

pub fn classic_dos() -> UiStyle {
    UiStyle {
        name: "Classic DOS",
        border_type: BorderType::Plain,
        border_color: Color::White,
        tree_vertical: "|   ",
        tree_branch: "|-- ",
        tree_last_child: "`-- ",
        tree_expanded: "v ",
        tree_collapsed: "> ",
        bar_filled: "#",
        bar_empty: ".",
        ext_pastille: " ## ",
        treemap_mode: TreemapMode::BlockChar('#'),
        treemap_dir_bg: Color::Rgb(0, 0, 128),
        treemap_empty_bg: Color::Black,
        sel_h: '-',
        sel_v: '|',
        sel_tl: '+',
        sel_tr: '+',
        sel_bl: '+',
        sel_br: '+',
        fg_directory: Color::LightBlue,
        fg_file: Color::Gray,
        fg_accent: Color::LightCyan,
        selected_bg: Color::White,
        selected_fg: Color::Black,
        statusbar_bg: Color::Rgb(0, 0, 128),
        pct_high: Color::LightRed,
        pct_mid: Color::Yellow,
        pct_low: Color::LightGreen,
        menu_bg: Color::Gray,
        menu_fg: Color::Black,
        menu_active_bg: Color::Black,
        menu_active_fg: Color::White,
        menu_drop_bg: Color::Gray,
        menu_drop_fg: Color::Black,
        menu_drop_sel_bg: Color::Black,
        menu_drop_sel_fg: Color::White,
        menu_shortcut_fg: Color::DarkGray,
    }
}

pub fn retro_cga() -> UiStyle {
    UiStyle {
        name: "Retro CGA",
        border_type: BorderType::Double,
        border_color: Color::Cyan,
        tree_vertical: "║   ",
        tree_branch: "╠── ",
        tree_last_child: "╚── ",
        tree_expanded: "V ",
        tree_collapsed: "> ",
        bar_filled: "#",
        bar_empty: " ",
        ext_pastille: " ## ",
        treemap_mode: TreemapMode::BlockChar('█'),
        treemap_dir_bg: Color::Rgb(0, 80, 80),
        treemap_empty_bg: Color::Black,
        sel_h: '═',
        sel_v: '║',
        sel_tl: '╔',
        sel_tr: '╗',
        sel_bl: '╚',
        sel_br: '╝',
        fg_directory: Color::LightCyan,
        fg_file: Color::White,
        fg_accent: Color::LightMagenta,
        selected_bg: Color::Cyan,
        selected_fg: Color::Black,
        statusbar_bg: Color::Rgb(0, 0, 128),
        pct_high: Color::LightMagenta,
        pct_mid: Color::LightCyan,
        pct_low: Color::LightGreen,
        menu_bg: Color::Blue,
        menu_fg: Color::White,
        menu_active_bg: Color::LightCyan,
        menu_active_fg: Color::Black,
        menu_drop_bg: Color::Blue,
        menu_drop_fg: Color::White,
        menu_drop_sel_bg: Color::LightCyan,
        menu_drop_sel_fg: Color::Black,
        menu_shortcut_fg: Color::Cyan,
    }
}

pub fn minimal() -> UiStyle {
    UiStyle {
        name: "Minimal",
        border_type: BorderType::Rounded,
        border_color: Color::Rgb(50, 50, 55),
        tree_vertical: "│   ",
        tree_branch: "├── ",
        tree_last_child: "└── ",
        tree_expanded: "- ",
        tree_collapsed: "+ ",
        bar_filled: "=",
        bar_empty: "-",
        ext_pastille: " :: ",
        treemap_mode: TreemapMode::HalfBlock,
        treemap_dir_bg: Color::Rgb(35, 35, 40),
        treemap_empty_bg: Color::Rgb(20, 20, 22),
        sel_h: '─',
        sel_v: '│',
        sel_tl: '┌',
        sel_tr: '┐',
        sel_bl: '└',
        sel_br: '┘',
        fg_directory: Color::Rgb(120, 140, 180),
        fg_file: Color::Rgb(140, 140, 140),
        fg_accent: Color::Rgb(180, 180, 200),
        selected_bg: Color::Rgb(50, 50, 60),
        selected_fg: Color::White,
        statusbar_bg: Color::Rgb(25, 25, 30),
        pct_high: Color::Rgb(200, 80, 80),
        pct_mid: Color::Rgb(200, 180, 80),
        pct_low: Color::Rgb(80, 180, 80),
        menu_bg: Color::Rgb(35, 35, 40),
        menu_fg: Color::Gray,
        menu_active_bg: Color::White,
        menu_active_fg: Color::Black,
        menu_drop_bg: Color::Rgb(40, 40, 48),
        menu_drop_fg: Color::Gray,
        menu_drop_sel_bg: Color::White,
        menu_drop_sel_fg: Color::Black,
        menu_shortcut_fg: Color::Rgb(80, 80, 90),
    }
}
